#!/usr/bin/env python3
"""Generate a custom two-line logo for the XLAT home screen.

Line 1: custom text (Chinese) -- small
Line 2: "XLAT" -- large
Outputs:
  img/logo_custom_preview.png  (viewable preview)
  src/theme/xlat_logo_custom.c (LVGL INDEXED_8BIT image, symbol name "xlat_logo")
"""

import re

from PIL import Image, ImageDraw, ImageFont

W, H = 130, 63
CN_FONT = "/System/Library/Fonts/Hiragino Sans GB.ttc"
EN_FONT = "/System/Library/Fonts/Supplemental/Arial Bold.ttf"

LINE1_TEXT = "小远小小远"
LINE1_SIZE = 23
LINE2_TEXT = "XLAT"
LINE2_SIZE = 44
LINE1_Y = 11   # vertical center of line 1
LINE2_Y = 44   # vertical center of line 2


def make_png():
    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)

    f1 = ImageFont.truetype(CN_FONT, LINE1_SIZE, index=0)
    f2 = ImageFont.truetype(EN_FONT, LINE2_SIZE)

    d.text((W / 2, LINE1_Y), LINE1_TEXT, font=f1, fill=(255, 255, 255, 255),
           anchor="mm")
    d.text((W / 2, LINE2_Y), LINE2_TEXT, font=f2, fill=(255, 255, 255, 255),
           anchor="mm")
    return img


def to_lvgl_indexed(img):
    """Convert RGBA image to LVGL v8 INDEXED_8BIT byte layout.

    Palette entry = (R, G, B, A), 256 entries; then one index byte per pixel.
    Index 0 is transparent. Every distinct opaque (R,G,B,A) pixel becomes a
    palette entry, so anti-aliasing is preserved exactly.
    """
    pixels = list(img.getdata())
    cmap = {}
    colors = []
    for p in pixels:
        if p[3] == 0:
            continue
        if p not in cmap:
            cmap[p] = len(colors) + 1
            colors.append(p)
    if len(colors) >= 256:
        raise RuntimeError("logo uses %d colors, too many for 8-bit indexed" % len(colors))

    palette = [(0, 0, 0, 0)] * 256
    for i, c in enumerate(colors):
        palette[i + 1] = c

    indices = [0 if p[3] == 0 else cmap[p] for p in pixels]

    out = bytearray()
    for (r, g, b, a) in palette:
        out += bytes((r, g, b, a))
    out += bytes(indices)
    assert len(out) == 256 * 4 + W * H
    return bytes(out)


def write_c(data, path, name):
    lines = [
        "/* Generated by tools/make_custom_logo.py */",
        "",
        "#ifdef LV_LVGL_H_INCLUDE_SIMPLE",
        '    #include "lvgl.h"',
        "#else",
        '    #include "lvgl/lvgl.h"',
        "#endif",
        "",
        "static const uint8_t %s_map[] = {" % name,
    ]
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        lines.append("    " + ", ".join("0x%02x" % b for b in chunk) + ",")
    lines += [
        "};",
        "",
        "const lv_img_dsc_t %s = {" % name,
        "    .header.cf = LV_IMG_CF_INDEXED_8BIT,",
        "    .header.always_zero = 0,",
        "    .header.reserved = 0,",
        "    .header.w = %d," % W,
        "    .header.h = %d," % H,
        "    .data_size = %d," % len(data),
        "    .data = %s_map," % name,
        "};",
        "",
    ]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    img = make_png()
    img.save("img/logo_custom_preview.png")
    print("preview saved: img/logo_custom_preview.png")
    data = to_lvgl_indexed(img)
    write_c(data, "src/theme/xlat_logo_custom.c", "xlat_logo")
    print("C file saved: src/theme/xlat_logo_custom.c (%d bytes)" % len(data))


if __name__ == "__main__":
    main()
