#!/usr/bin/env python3
"""Convert the user's "小远" image into the LVGL top-left logo.

Only the left character ("小") is recolored to white; the right character
("远") keeps its original color.
"""

import numpy as np
import sys
from PIL import Image, ImageDraw

OUT_PREVIEW = "img/logo_user_preview.png"
OUT_C = "src/theme/xlat_logo_user.c"

LOGO_MAX_H = 55


def remove_white_background(im):
    im = im.convert("RGBA")
    w, h = im.size
    MARKER = (0, 0, 0, 0)
    seeds = [
        (0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1),
        (w // 2, 0), (0, h // 2), (w // 2, h - 1), (w - 1, h // 2),
        (w // 4, 0), (3 * w // 4, 0), (w // 4, h - 1), (3 * w // 4, h - 1),
    ]
    for s in seeds:
        ImageDraw.floodfill(im, s, MARKER, thresh=52)
    return im


def recolor_left_character_white(logo):
    """Keep "远" (right) original; recolor "小" (left) to white."""
    arr = np.asarray(logo).copy()
    alpha = arr[:, :, 3]
    cols = alpha.sum(axis=0)

    # find the largest horizontal gap (between the two characters)
    runs = []
    start = None
    for i in range(len(cols)):
        if cols[i] == 0 and start is None:
            start = i
        elif cols[i] > 0 and start is not None:
            runs.append((start, i - 1))
            start = None
    if start is not None:
        runs.append((start, len(cols) - 1))

    gap = max(runs, key=lambda r: r[1] - r[0])
    split = (gap[0] + gap[1]) // 2

    mask = (alpha > 0)
    left = np.zeros_like(mask)
    left[:, :split] = True
    white = mask & left
    arr[:, :, 0][white] = 255
    arr[:, :, 1][white] = 255
    arr[:, :, 2][white] = 255
    return Image.fromarray(arr)


def to_lvgl_true_color_alpha(img):
    out = bytearray()
    for p in img.getdata():
        r, g, b, a = p
        c = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        out += bytes((c & 0xFF, (c >> 8) & 0xFF, a))
    return bytes(out)


def write_c(data, path, name, w, h):
    lines = [
        "/* Generated by tools/make_user_logo.py */",
        "",
        "#ifdef LV_LVGL_H_INCLUDE_SIMPLE",
        '    #include "lvgl.h"',
        "#else",
        '    #include "lvgl/lvgl.h"',
        "#endif",
        "",
        "static const uint8_t %s_map[] = {" % name,
    ]
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        lines.append("    " + ", ".join("0x%02x" % b for b in chunk) + ",")
    lines += [
        "};",
        "",
        "const lv_img_dsc_t %s = {" % name,
        "    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,",
        "    .header.always_zero = 0,",
        "    .header.reserved = 0,",
        "    .header.w = %d," % w,
        "    .header.h = %d," % h,
        "    .data_size = %d," % len(data),
        "    .data = %s_map," % name,
        "};",
        "",
    ]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    if len(sys.argv) < 2:
        print("Usage: make_user_logo.py <source_image.png>")
        sys.exit(1)
    logo = Image.open(sys.argv[1]).convert("RGBA")
    logo = remove_white_background(logo)
    bbox = logo.getbbox()
    if bbox is None:
        raise SystemExit("no subject found")
    logo = logo.crop(bbox)
    logo = recolor_left_character_white(logo)

    ratio = LOGO_MAX_H / logo.height
    new_w = max(1, int(logo.width * ratio))
    new_h = LOGO_MAX_H
    logo = logo.resize((new_w, new_h), Image.LANCZOS)

    logo.save(OUT_PREVIEW)
    data = to_lvgl_true_color_alpha(logo)
    write_c(data, OUT_C, "xlat_logo", new_w, new_h)
    print("saved", OUT_PREVIEW, "(%dx%d)" % (new_w, new_h))
    print("saved", OUT_C, "(%d bytes)" % len(data))


if __name__ == "__main__":
    main()
