#!/usr/bin/env python3
"""Convert a PNG into an LVGL v8 TRUE_COLOR (RGB565) C source file.

Usage:
    png_to_lvgl565.py <input.png> <output.c> <image_name>

The output is a full-screen friendly LVGL image descriptor:
    const lv_img_dsc_t <image_name> = { .header.cf = LV_IMG_CF_TRUE_COLOR, ... };
Floyd-Steinberg dithering is applied before quantizing to RGB565.
"""

import sys

from PIL import Image


def to565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def dither_to_rgb565(pixels, w, h):
    """In-place Floyd-Steinberg dithering, returns list of 16-bit values."""
    buf = [[list(p) for p in pixels[y * w:(y + 1) * w]] for y in range(h)]
    out = [[0] * w for _ in range(h)]
    for y in range(h):
        for x in range(w):
            r, g, b = buf[y][x]
            old_r, old_g, old_b = r, g, b
            nr = ((r >> 3) << 3) | (r >> 5 & 1)
            ng = ((g >> 2) << 2) | (g >> 4 & 1)
            nb = ((b >> 3) << 3) | (b >> 5 & 1)
            out[y][x] = to565(nr, ng, nb)
            er, eg, eb = old_r - nr, old_g - ng, old_b - nb
            for dx, dy, wgt in ((-1, 1, 3), (0, 1, 3), (1, 1, 2), (1, 0, 1)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < w and 0 <= ny < h:
                    buf[ny][nx][0] = max(0, min(255, buf[ny][nx][0] + er * wgt // 8))
                    buf[ny][nx][1] = max(0, min(255, buf[ny][nx][1] + eg * wgt // 8))
                    buf[ny][nx][2] = max(0, min(255, buf[ny][nx][2] + eb * wgt // 8))
    return out


def main():
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(1)
    src, dst, name = sys.argv[1], sys.argv[2], sys.argv[3]

    im = Image.open(src).convert("RGB")
    w, h = im.size
    data = dither_to_rgb565(list(im.getdata()), w, h)

    tokens = []
    for y in range(h):
        for x in range(w):
            v = data[y][x]
            tokens.append(f"0x{v & 0xFF:02x}")
            tokens.append(f"0x{(v >> 8) & 0xFF:02x}")

    out = []
    out.append("/* Generated by tools/png_to_lvgl565.py from %s */" % src)
    out.append("")
    out.append("#ifdef LV_LVGL_H_INCLUDE_SIMPLE")
    out.append('    #include "lvgl.h"')
    out.append("#else")
    out.append('    #include "lvgl/lvgl.h"')
    out.append("#endif")
    out.append("")
    out.append("static const uint8_t %s_map[] = {" % name)
    for i in range(0, len(tokens), 16):
        line = "    " + ", ".join(tokens[i:i + 16])
        if i + 16 < len(tokens):
            line += ","
        out.append(line)
    out.append("};")
    out.append("")
    out.append("const lv_img_dsc_t %s = {" % name)
    out.append("    .header.cf = LV_IMG_CF_TRUE_COLOR,")
    out.append("    .header.always_zero = 0,")
    out.append("    .header.reserved = 0,")
    out.append("    .header.w = %d," % w)
    out.append("    .header.h = %d," % h)
    out.append("    .data_size = %d," % (w * h * 2))
    out.append("    .data = %s_map," % name)
    out.append("};")
    out.append("")
    with open(dst, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print("wrote %s (%dx%d, %d bytes)" % (dst, w, h, w * h * 2))


if __name__ == "__main__":
    main()
